# Generated by Django 4.0.4 on 2022-05-27 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('priority', models.CharField(choices=(('sem prioridade', 'sem prioridade'), ('alta', 'alta'), ('média', 'média'), ('baixa', 'baixa')), max_length=20)),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='lists.list')),
            ],
        ),
    ]
